version: '3'
services:
  app:
    build: .
    depends_on:
      - db
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"
