name: A workflow pushing the app
on: push

jobs:
  build:
    name: on push action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn package
      - name: Run docker compose
        run: docker-compose up --abort-on-container-exit
     
